#!/bin/bash
cd ~/los22
C=device/samsung/universal7420-common; V=vendor/samsung/universal7420-common/proprietary/vendor
ok(){ echo "  [OK]  $1"; }; bad(){ echo "  [!!]  $1"; }
chk(){ if eval "$2" >/dev/null 2>&1; then ok "$1"; else bad "$1"; fi; }
echo "== SIM / HIDL"
chk "libhidl kEnforceVintfManifest=true (SIM, BT)" "grep -q 'kEnforceVintfManifest = true; // noblelte' system/libhidl/transport/ServiceManagement.cpp"
chk "rild from device"            "[ \$(md5sum < $V/bin/hw/rild | cut -c1-32) = 6f1e92ad7c389e11aee95d172291d244 ]"
chk "libril_sem.so lib64"         "[ -f $V/lib64/libril_sem.so ]"
echo "== cgroup / lag"
chk "cgroups.json v2 Mode/UID/GID" "grep -q '\"UID\": \"system\"' $C/configs/cgroups.json"
echo "== camera / fingerprint shims"
chk "libexynoscamera lib   -> shim" "readelf -d $V/lib/libexynoscamera.so | grep -q libexynoscamera_shim"
chk "libexynoscamera lib64 -> shim" "readelf -d $V/lib64/libexynoscamera.so | grep -q libexynoscamera_shim"
chk "libbauthserver lib   -> shim"  "readelf -d $V/lib/libbauthserver.so | grep -q libbauthtzcommon_shim"
chk "libbauthserver lib64 -> shim"  "readelf -d $V/lib64/libbauthserver.so | grep -q libbauthtzcommon_shim"
echo "== fingerprint spam (until HAL added)"
chk "manifest: no HIDL fingerprint <hal>" "! grep -q biometrics.fingerprint $C/manifest.xml"
chk "fingerprint.xml copied (HAL present)" "grep -q android.hardware.fingerprint.xml $C/device-common.mk"
echo "== Wi-Fi"
chk "kernel: free_initmem skipped"  "grep -q 'noblelte: free_initmem' kernel/samsung/universal7420/init/main.c"
chk "kernel: IFA_FLAGS uapi"        "grep -q IFA_FLAGS kernel/samsung/universal7420/include/uapi/linux/if_addr.h"
chk "kernel: IFA_FLAGS ipv4"        "grep -q 'IFA_FLAGS, ifa->ifa_flags' kernel/samsung/universal7420/net/ipv4/devinet.c"
chk "kernel: IFA_FLAGS ipv6"        "grep -q 'IFA_FLAGS, ifa->flags' kernel/samsung/universal7420/net/ipv6/addrconf.c"
chk "wifiloader in vendor blobs"    "[ -f vendor/samsung/noblelte/proprietary/vendor/bin/wifiloader ]"
chk "NetworkStack clean (no am in progress)" "[ ! -d packages/modules/NetworkStack/.git/rebase-apply ] && [ ! -d \$(cd packages/modules/NetworkStack && git rev-parse --git-dir)/rebase-apply ]"
echo "== boot fixes (earlier)"
chk "OVERRIDE_PRODUCT_COMPRESSED_APEX" "grep -q OVERRIDE_PRODUCT_COMPRESSED_APEX device/samsung/noblelte/device.mk"
chk "bpf rename2"                      "grep -q rename2 kernel/samsung/universal7420/kernel/bpf/inode.c"
chk "audio threadpool commented"       "grep -q '//.*ABinderProcess_setThreadPoolMaxThreadCount(1)' hardware/interfaces/audio/common/all-versions/default/service/service.cpp"
# --- thermal (CHANGES §48-49) ---
grep -q "android.hardware.thermal" ~/los22/device/samsung/universal7420-common/manifest.xml && echo "OK thermal manifest" || echo "MISSING thermal manifest"
grep -q "exynos-therm" ~/los22/hardware/samsung_slsi-linaro/exynos/thermal/thermal_exynos.cpp && echo "OK thermal zones" || echo "MISSING thermal zones"
grep -q "noblelte: filterType" ~/los22/hardware/samsung_slsi-linaro/exynos/thermal/Thermal.cpp && echo "OK thermal filterType" || echo "MISSING thermal filterType"
# --- audio/mic/bt (CHANGES §45-47) ---
grep -q "pcm_dev_list.next != NULL" ~/los22/device/samsung/universal7420-common/hardware/audio/audio_hw.c && echo "OK audio NULL fix" || echo "MISSING audio NULL fix"
grep -q "^debug.stagefright.ccodec=4" ~/los22/device/samsung/universal7420-common/system.prop && echo "OK ccodec=4" || echo "MISSING ccodec=4"
grep -q "bluetooth.profile.a2dp.source.enabled=true" ~/los22/device/samsung/noblelte/device.mk && echo "OK bt a2dp prop" || echo "MISSING bt a2dp prop"
[ ! -d ~/los22/hardware/samsung/audio ] && echo "OK unused hardware/samsung/audio removed" || echo "WARN hardware/samsung/audio still present"
grep -q "^# CONFIG_SND_DUMMY is not set" ~/los22/kernel/samsung/universal7420/arch/arm64/configs/exynos7420-noblelte_defconfig && echo "OK kernel SND_DUMMY off" || echo "MISSING kernel SND_DUMMY off"
grep -q "UartPort = /dev/ttySAC4" ~/los22/device/samsung/noblelte/bluetooth/bt_vendor.conf && echo "OK bt UartPort" || echo "MISSING bt UartPort"
grep -q "uses_percentage_samples=true" ~/los22/device/samsung/noblelte/device.mk && echo "OK fp percentage prop" || echo "MISSING fp percentage prop"
grep -q "libsensor_shim_gpsd" ~/los22/device/samsung/universal7420-common/device-common.mk && echo "OK gpsd shim package" || echo "MISSING gpsd shim package"
~/los22/prebuilts/clang/host/linux-x86/llvm-binutils-stable/llvm-readelf -d ~/los22/vendor/samsung/universal7420-common/proprietary/vendor/bin/hw/gpsd | grep -q libsensor_shim_gpsd && echo "OK gpsd blob patched" || echo "MISSING gpsd blob patched"
grep -q 'IgnoreJniTime="false"' ~/los22/vendor/samsung/universal7420-common/proprietary/vendor/etc/gnss/gps.xml && echo "OK gps.xml tuned" || echo "MISSING gps.xml tuned"
! grep -q "IDrmFactory/widevine" ~/los22/device/samsung/universal7420-common/manifest.xml && echo "OK widevine not declared" || echo "MISSING widevine undeclare"
! grep -q "drm@1.1-service.widevine" ~/los22/vendor/samsung/universal7420-common/universal7420-common-vendor.mk && echo "OK widevine service not shipped" || echo "MISSING widevine service removal"
