#!/bin/bash
# noblelte LOS22 — "nuclear" consolidation of every device-proven fix into the SOURCE.
# Usage:
#   bash ~/nuke_fix.sh check    # read-only: report what is missing (no changes)
#   bash ~/nuke_fix.sh apply    # apply missing blob fixes to the tree (backups in ~/blobsrc/nuke_bak_<date>)
# After `apply`: run `bash ~/nuke_fix.sh check` again -> must print 0 MISSING, then build.
#
# Why this is needed (CHANGES §53/§54):
#  - A15 fsgen converts PRODUCT_COPY_FILES into arm64 prebuilt modules: a *.so copied to vendor/lib/
#    lands in vendor/lib64 -> packaging conflict. So 32-bit blobs MUST be cc_prebuilt_library_shared
#    modules with compile_multilib "32" (generated below). 64-bit blobs are fine as PRODUCT_COPY_FILES.
#  - The Fakeman RIL kit (§30) that made SIM work needs radio@2.2 + radio.bridge@2.1 (+ whatever else
#    rild/libril_sem/libsec-ril NEED). They are taken from the Fakeman LOS21 reference image (§29).

set -u
MODE=${1:-check}
TOP=~/los22
cd $TOP || exit 1
RE=$TOP/prebuilts/clang/host/linux-x86/llvm-binutils-stable/llvm-readelf
C=vendor/samsung/universal7420-common
N=vendor/samsung/noblelte
CP=$C/proprietary/vendor
NP=$N/proprietary/vendor
O=out/target/product/noblelte/system
REF=/mnt/los21
MISSING=0
BAK=~/blobsrc/nuke_bak_$(date +%m%d_%H%M)
say(){ echo "$@"; }
miss(){ echo "MISSING  $*"; MISSING=$((MISSING+1)); }

# ---------- 0. reference image (Fakeman LOS21) ----------
if ! mountpoint -q $REF; then
  sudo mkdir -p $REF && sudo mount -o loop,ro ~/blobsrc/los21_system.img $REF || { echo "cannot mount ~/blobsrc/los21_system.img"; exit 1; }
fi
REFV=$(ls -d $REF/system/vendor $REF/vendor 2>/dev/null | head -1)
[ -d "$REFV/lib64" ] || { echo "reference vendor dir not found under $REF"; exit 1; }
say "== reference vendor: $REFV"

[ "$MODE" = apply ] && { mkdir -p $BAK; cp $C/universal7420-common-vendor.mk $N/noblelte-vendor.mk $BAK/; say "== backups: $BAK"; }

# ---------- 1. 64-bit dependency closure for RIL + GPS (vendor namespace) ----------
say "== [1] 64-bit NEEDED closure: rild, libril_sem, libsec-ril, libsec-ril-dsds, gpsd"
have64(){ # installed/installable for the vendor default namespace?
  case $1 in libc.so|libm.so|libdl.so|liblog.so|libicuuc.so|libicui18n.so|libc++.so) return 0;; esac  # bionic/APEX (runtime, i18n)
  [ -e $CP/lib64/$1 ] && grep -q "proprietary/vendor/lib64/$1:" $C/universal7420-common-vendor.mk && return 0
  [ -e $NP/lib64/$1 ] && grep -q "proprietary/vendor/lib64/$1:" $N/noblelte-vendor.mk && return 0
  [ -e $O/vendor/lib64/$1 ] || [ -e $O/lib64/$1 ]
}
queue="$CP/bin/hw/rild $CP/lib64/libril_sem.so $CP/lib64/libsec-ril.so $CP/lib64/libsec-ril-dsds.so $CP/bin/hw/gpsd"
seen=" "
while [ -n "$queue" ]; do
  set -- $queue; f=$1; shift; queue="$*"
  for lib in $($RE -d "$f" 2>/dev/null | sed -n 's/.*NEEDED.*\[\(.*\)\]/\1/p'); do
    case "$seen" in *" $lib "*) continue;; esac; seen="$seen$lib "
    if have64 $lib; then
      [ -e $CP/lib64/$lib ] && queue="$queue $CP/lib64/$lib"
      continue
    fi
    src=$(ls $REFV/lib64/$lib $O/system_ext/lib64/$lib 2>/dev/null | head -1)
    if [ -z "$src" ]; then miss "64-bit $lib (no source found in LOS21 ref or out/)"; continue; fi
    file -L "$src" | grep -q "ELF 64" || { miss "64-bit $lib: $src is not ELF64"; continue; }
    miss "64-bit $lib  <- $src"
    if [ "$MODE" = apply ]; then
      cp -f "$src" $CP/lib64/$lib
      echo "PRODUCT_COPY_FILES += $CP/lib64/$lib:\$(TARGET_COPY_OUT_VENDOR)/lib64/$lib" >> $C/universal7420-common-vendor.mk
      say "   applied: $CP/lib64/$lib + PRODUCT_COPY_FILES"
      queue="$queue $CP/lib64/$lib"
    fi
  done
done
# libril_sem itself must be installed (it was lost in the first full build)
grep -q "proprietary/vendor/lib64/libril_sem.so:" $C/universal7420-common-vendor.mk || {
  miss "PRODUCT_COPY_FILES libril_sem.so (lib64)"
  [ "$MODE" = apply ] && echo "PRODUCT_COPY_FILES += $CP/lib64/libril_sem.so:\$(TARGET_COPY_OUT_VENDOR)/lib64/libril_sem.so" >> $C/universal7420-common-vendor.mk
}

# ---------- 2. 32-bit blobs never installed -> cc_prebuilt modules (compile_multilib 32) ----------
say "== [2] 32-bit blobs in proprietary/vendor/lib not installed in out/"
gen_bp(){ # $1=tree(C|N) path  $2=bp file
  local base=$1 bp=$2 pkgs=""
  local tmp=$(mktemp)
  echo "// Generated by nuke_fix.sh — 32-bit vendor blobs (A15 fsgen breaks PRODUCT_COPY_FILES into vendor/lib)" > $tmp
  (cd $base/proprietary/vendor && find lib -maxdepth 2 -name '*.so' -type f) | sort | while read rel; do
    f=$base/proprietary/vendor/$rel
    [ -e $O/vendor/$rel ] && continue                       # already installed
    grep -q "srcs: \[\"$rel\"\]" $base/proprietary/vendor/Android.bp 2>/dev/null && [ "$MODE" = check ] && continue  # declared by us
    file -L "$f" | grep -q "ELF 32" || continue             # skip arch-mismatch leftovers
    name=$(basename $rel .so); sub=$(dirname $rel); sub=${sub#lib}; sub=${sub#/}
    mod="nl32_${name//[@.]/_}"
    echo "MISS32 $rel -> $mod" >&2
    cat >> $tmp <<EOF

cc_prebuilt_library_shared {
    name: "$mod",
    stem: "$name",
    owner: "samsung",
    vendor: true,
    compile_multilib: "32",
    check_elf_files: false,
    strip: { none: true },
$( [ -n "$sub" ] && echo "    relative_install_path: \"$sub\"," )
    target: { android_arm: { srcs: ["$rel"] } },
}
EOF
    echo "$mod" >> $tmp.pkgs
  done
  if [ -s $tmp.pkgs ]; then
    MISSING=$((MISSING+$(wc -l < $tmp.pkgs)))
    if [ "$MODE" = apply ]; then
      cp $tmp $base/$bp; say "   wrote $base/$bp"
      echo "PRODUCT_PACKAGES += $(tr '\n' ' ' < $tmp.pkgs)" >> $base/$(basename $base)-vendor.mk
      say "   applied: $base/$bp + PRODUCT_PACKAGES ($(wc -l < $tmp.pkgs) modules)"
    fi
  fi
  rm -f $tmp $tmp.pkgs
}
for base in $C $N; do
  if [ -e $base/proprietary/vendor/Android.bp ] && ! grep -q "Generated by nuke_fix.sh" $base/proprietary/vendor/Android.bp; then
    miss "$base/proprietary/vendor/Android.bp exists (not ours) - cannot place generated modules"; continue
  fi
  if [ "$MODE" = apply ] && grep -q "Generated by nuke_fix.sh" $base/proprietary/vendor/Android.bp 2>/dev/null; then
    say "   $base: generated Android.bp already present - not regenerating"; continue
  fi
  gen_bp $base proprietary/vendor/Android.bp 2> >(sed 's/^/MISSING  /')
  sleep 1
done

# ---------- 3. shim NEEDED on 32-bit camera/fingerprint blobs (§31) ----------
say "== [3] shims on 32-bit blobs"
for pair in "$CP/lib/libexynoscamera.so libexynoscamera_shim.so" "$CP/lib/libbauthserver.so libbauthtzcommon_shim.so"; do
  set -- $pair
  n=$($RE -d $1 | grep -c "\[$2\]")
  if [ "$n" = 1 ]; then continue; fi
  miss "$1 has $n x NEEDED $2 (want 1)"
  if [ "$MODE" = apply ]; then cp $1 $BAK/$(basename $1).pre_shimfix; patchelf --remove-needed $2 $1; patchelf --add-needed $2 $1; say "   applied: $1 -> exactly 1 x $2"; fi
done

# ---------- 4. GApps tolerance: privapp permissions log (tested on device 09-25) ----------
say "== [4] ro.control_privapp_permissions=log"
SP=device/samsung/universal7420-common/system.prop
grep -q "^ro.control_privapp_permissions=log" $SP || {
  miss "$SP ro.control_privapp_permissions=log"
  [ "$MODE" = apply ] && echo "ro.control_privapp_permissions=log" >> $SP
}

# ---------- 5. all earlier fixes (§31-§52) ----------
say "== [5] audit_src.sh"
~/audit_src.sh | grep -vE "^\s*\[OK\]|^OK|^==" | sed 's/^/MISSING  audit: /' | tee /tmp/nuke_audit.txt
MISSING=$((MISSING+$(grep -c . /tmp/nuke_audit.txt)))

say "=================================================="
say "MODE=$MODE  MISSING=$MISSING"
[ "$MODE" = check ] && [ $MISSING -gt 0 ] && say "-> run: bash ~/nuke_fix.sh apply ; then check again"
[ "$MODE" = check ] && [ $MISSING -eq 0 ] && say "-> source complete. Build: source build/envsetup.sh && breakfast noblelte && m bacon -j4"
